from enum import Enum


class ButtonEventKey(Enum):
  BUTTON_CONNECT = '_button_connect_'
  BUTTON_DISCONNECT = '_button_disconnect_'
  BUTTON_NEW_HUMAN = '_button_new_human_'
  BUTTON_ADD_HUMAN = '_button_add_human_'
  BUTTON_SAVE_HUMAN = '_button_save_human_'
  BUTTON_UPDATE_HUMAN = '_button_update_human_'
  BUTTON_CANCEL_HUMAN = '_button_cancel_human_'
  BUTTON_DELETE_HUMAN = '_button_delete_human_'
  BUTTON_NEW_DEVICE = '_button_new_device_'
  BUTTON_ADD_DEVICE = '_button_add_device_'
  BUTTON_SAVE_DEVICE = '_button_save_device_'
  BUTTON_UPDATE_DEVICE = '_button_update_device_'
  BUTTON_CANCEL_DEVICE = '_button_cancel_device_'
  BUTTON_DELETE_DEVICE = '_button_delete_device_'
  BUTTON_NEW_ROOM = '_button_new_room_'
  BUTTON_ADD_ROOM = '_button_add_room_'
  BUTTON_SAVE_ROOM = '_button_save_room_'
  BUTTON_UPDATE_ROOM = '_button_update_room_'
  BUTTON_CANCEL_ROOM = '_button_cancel_room_'
  BUTTON_DELETE_ROOM = '_button_delete_room_'
  BUTTON_NEW_DOOR = '_button_new_door_'
  BUTTON_ADD_DOOR = '_button_add_door_'
  BUTTON_SAVE_DOOR = '_button_save_door_'
  BUTTON_UPDATE_DOOR = '_button_update_door_'
  BUTTON_CANCEL_DOOR = '_button_cancel_door_'
  BUTTON_DELETE_DOOR = '_button_delete_door_'
  BUTTON_NEW_WINDOW = '_button_new_window_'
  BUTTON_ADD_WINDOW = '_button_add_window_'
  BUTTON_SAVE_WINDOW = '_button_save_window_'
  BUTTON_UPDATE_WINDOW = '_button_update_window_'
  BUTTON_CANCEL_WINDOW = '_button_cancel_window_'
  BUTTON_DELETE_WINDOW = '_button_delete_window_'


class TableEventKey(Enum):
  TABLE_HUMAN = '_table_human_row_'
  TABLE_DEVICE = '_table_device_row_'
  TABLE_ROOM = '_table_room_row_'
  TABLE_DOOR = '_table_door_row_'
  TABLE_WINDOW = '_table_window_row_'


class FieldEventKey(Enum):
  FIELD_HUMAN_NAME = '_field_human_name_'
  FIELD_HUMAN_LOCATION = '_field_human_location_'
  FIELD_DEVICE_TYPE = '_field_device_type_'
  FIELD_DEVICE_NAME = '_field_device_name_'
  FIELD_DEVICE_LOCATION = '_field_device_location_'
  FIELD_ROOM_TYPE = '_field_room_type_'
  FIELD_ROOM_NAME = '_field_room_name_'
  FIELD_DOOR_ROOM_A = '_field_doom_room_a_'
  FIELD_DOOR_ROOM_B = '_field_doom_room_b_'
  FIELD_DOOR_NAME = '_field_doom_name_'
  FIELD_DOOR_IS_OPEN = '_field_doom_is_open_'
  FIELD_DOOR_IS_CLOSE = '_field_doom_is_close_'
  FIELD_WINDOW_ROOM = '_field_window_room_'
  FIELD_WINDOW_NAME = '_field_window_name_'
  FIELD_WINDOW_IS_OPEN = '_field_window_is_open_'
  FIELD_WINDOW_IS_CLOSE = '_field_window_is_close_'
  FIELD_CONNECTION_LEFT = '_field_connection_left_'
  FIELD_CONNECTION_RIGHT = '_field_connection_right_'
  FIELD_CONNECTION_NAME = '_field_connection_name_'
